### ISSUE TITLE
Missing Credentials in Config?

### ISSUE THREAD

**Issue by djMax** [alxolr/elasticmq-node-tutorial#1]
I'm trying to use this approach to test an SQS module in github actions and getting this error:

```
SQS error { SQSError: SQS receive message failed: Missing credentials in config
    at toSQSError (/home/runner/work/configured-sqs-client/configured-sqs-client/node_modules/sqs-consumer/dist/consumer.js:41:22)
    at Consumer.receiveMessage (/home/runner/work/configured-sqs-client/configured-sqs-client/node_modules/sqs-consumer/dist/consumer.js:137:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'SQSError',
  code: 'CredentialsError',
  statusCode: 400,
  region: undefined,
  retryable: false,
  hostname: undefined,
  time: 2020-02-02T05:46:51.549Z }
```

The project is here:
https://github.com/gas-buddy/configured-sqs-client

I would assume this is the SQS client and NOT the elasticmq server, but your excellent writeup doesn't mention anything about needing placeholder SQS creds. Any ideas on what's failing here? Thanks for any insight you can provide!

--Max

**Comment by djMax** [comment]
It turned out I needed to pass dummy values for the credentials for some reason (probably the sqs-consumer module somehow invading the process)

```
    accessKeyId: 'key',
    secretAccessKey: 'secret',
    sessionToken: 'token',
```
